name: Build Windows Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Build directory exists: $(if (Test-Path build) { 'Yes' } else { 'No' })"
          if (Test-Path build) { echo "Build contents: $(Get-ChildItem build)" }
        shell: powershell
      
      - name: Generate icons (with error handling)
        run: npm run icons
        continue-on-error: true
      
      - name: Build application
        run: npm run build
      
      - name: Debug build output
        run: |
          echo "Dist directory exists: $(if (Test-Path dist) { 'Yes' } else { 'No' })"
          if (Test-Path dist) { echo "Dist contents: $(Get-ChildItem dist -Recurse)" }
        shell: powershell
        continue-on-error: true
      
      - name: Build Windows installer
        run: npm run make
      
      - name: Debug output directory
        run: |
          echo "Out directory exists: $(if (Test-Path out) { 'Yes' } else { 'No' })"
          if (Test-Path out) { echo "Out contents: $(Get-ChildItem out -Recurse)" }
        shell: powershell
        continue-on-error: true
      
      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: out/make/squirrel.windows/**/*.exe
      
      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: out/make/squirrel.windows/**/*.exe
          draft: false
          prerelease: false
          generate_release_notes: true 